# app_config.yaml
settings:
  title: "AI Alchemy Station"
  icon: "ğŸ”¥"

modules:
  
  code_review:
    enable: true
    file: "code_reviewer.py"
    name: "ä»£ç å®¡è®¡ (Reader)"
    icon: "ğŸ§"

  # omni_run:
  #   enable: true
  #   file: "omni_runner.py"
  #   name: "OmniControl å¯åŠ¨å™¨"
  #   icon: "ğŸƒ"

  omni_and_motionlcm_run:
    enable: true
    file: "omni_and_MotionLCM_runner.py"
    name: "OmniControl + MotionLCM å¯åŠ¨å™¨"
    icon: "ğŸ¤–"
  video_gallery:
    enable: true
    file: "video_gallery.py"
    name: "è§†é¢‘ç”»å»Š"
    icon: "ğŸ¥"
  HumanML3DConverter:
    enable: true
    file: "motion_converter.py"
    name: "HumanML3Dä¸‡èƒ½æ ¼å¼è½¬æ¢å™¨"
    icon: "ğŸ¥”"


  # === æ–°å¢çš„éƒ¨åˆ† ===
  gvhmr_run:
    enable: true
    file: "GVHMR.py"   # å¯¹åº” modules/gvhmr_module.py æ–‡ä»¶å
    name: "GVHMR åŠ¨ä½œæå–"      # ä¾§è¾¹æ æ˜¾ç¤ºçš„åç§°
    icon: "ğŸ’ƒ"                # å›¾æ ‡
  # ==================

  train:
    enable: true
    file: "training.py"
    name: "ç‚¼ä¸¹/è®­ç»ƒæ¨¡å¼"   # è¿™é‡Œä¼šè¦†ç›–ç±»é‡Œçš„ self.name
    icon: "âš—ï¸"       # è¿™é‡Œä¼šè¦†ç›–ç±»é‡Œçš„ self.icon


  inference:
    enable: true
    file: "inference.py"
    name: "æ¨ç†æ¨¡å¼ (Inference)"
    icon: "ğŸ”®"

  evaluation:
    enable: true
    file: "evaluation.py"
    name: "æˆ‘è¦è¯„ä¼° (Eval)"
    icon: "ğŸ“Š"

  render:
    enable: true
    file: "render.py"
    name: "çœ‹çœ‹ä½ çš„ï¼šæ¸²æŸ“"
    icon: "ğŸ¬"