# app_config.yaml
settings:
  title: "AI Alchemy Station"
  icon: "ğŸ”¥"

modules:
  train:
    enable: true
    file: "training.py"
    name: "ç‚¼ä¸¹æ¨¡å¼"   # è¿™é‡Œä¼šè¦†ç›–ç±»é‡Œçš„ self.name
    icon: "âš—ï¸"       # è¿™é‡Œä¼šè¦†ç›–ç±»é‡Œçš„ self.icon

  code_review:
    enable: true
    file: "code_reviewer.py"
    name: "ä»£ç å®¡è®¡ (Reader)"
    icon: "ğŸ§"

  # omni_run:
  #   enable: true
  #   file: "omni_runner.py"
  #   name: "OmniControl å¯åŠ¨å™¨"
  #   icon: "ğŸƒ"

  omni_and_motionlcm_run:
    enable: true
    file: "omni_and_MotionLCM_runner.py"
    name: "OmniControl + MotionLCM å¯åŠ¨å™¨"
    icon: "ğŸ¤–"
  video_gallery:
    enable: true
    file: "video_gallery.py"
    name: "è§†é¢‘ç”»å»Š"
    icon: "ğŸ¥"
  HumanML3DConverter:
    enable: true
    file: "motion_converter.py"
    name: "HumanML3Dä¸‡èƒ½æ ¼å¼è½¬æ¢å™¨"
    icon: "ğŸ¥”"

  
